### ISSUE TITLE
Admin panel error?

### ISSUE THREAD

**Issue by grctest** [cyberpunk-ventures/glasnost#7]
```
02:02:32.106 [info] Starting config update...
02:02:32.130 [info] Finishing config update...
02:02:32.153 request_id=jghitbt511sna12b0s8rni56bdl2nbug [info] Sent 500 in 48ms
02:02:32.172 [error] #PID<0.482.0> running Glasnost.Web.Endpoint terminated
Server: mydomain.tldt:80 (http)
Request: POST /admin/command_and_control
** (exit) an exception was raised:
    ** (Protocol.UndefinedError) protocol String.Chars not implemented for %HTTP                                                                                                             oison.Error{id: nil, reason: :nxdomain}
        (elixir) lib/string/chars.ex:3: String.Chars.impl_for!/1
        (elixir) lib/string/chars.ex:17: String.Chars.to_string/1
        (glasnost) lib/glasnost/web/controllers/admin_controller.ex:21: Glasnost                                                                                                             .Web.AdminController.command_and_control/2
        (glasnost) lib/glasnost/web/controllers/admin_controller.ex:1: Glasnost.                                                                                                             Web.AdminController.action/2
        (glasnost) lib/glasnost/web/controllers/admin_controller.ex:1: Glasnost.                                                                                                             Web.AdminController.phoenix_controller_pipeline/2
        (glasnost) lib/glasnost/web/endpoint.ex:1: Glasnost.Web.Endpoint.instrum                                                                                                             ent/4
        (phoenix) lib/phoenix/router.ex:277: Phoenix.Router.__call__/1
        (glasnost) lib/glasnost/web/endpoint.ex:1: Glasnost.Web.Endpoint.plug_bu                                                                                                             ilder_call/2
```

Internal server error when specifying a configuration URL. Is there a format that the config URL needs to follow?

On another note, if my server crashes how do I maintain the previous instance of docker? By starting up the docker container again won't the admin page reset (potentially enabling a malicious user to gain access to the admin panel?)

**Comment by ontofractal** [comment]
> Is there a format that the config URL needs to follow?

Just the usual URL format including the `http` or `https` prefix. The url should point to a raw (as in github gist raw) valid JSON file. 

> By starting up the docker container again won't the admin page reset (potentially enabling a malicious user to gain access to the admin panel?)

Yep, Glasnost is in alpha and current admin workflow isn't ready for production yet. I will  implement proper authorization and authentication soon.

**Comment by grctest** [comment]
Ah, so I need to specify the full URL? I thought I just had to provide a keyword like 'secretadminpanel' instead of 'http://domain.tld/secretadminpanel' good to know 👍
